# Generated by Django 2.0 on 2019-01-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('job_link', models.URLField(null=True)),
                ('proposal_link', models.URLField(null=True)),
                ('num_of_upvotes', models.IntegerField(default=0)),
                ('proposal_revised', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Proposal'),
        ),
    ]
