# Generated by Django 2.0 on 2019-01-28 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
