# Generated by Django 2.0 on 2019-01-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20190128_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='source',
        ),
    ]
