# Generated by Django 2.0 on 2019-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20190128_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='num_of_downvotes',
            field=models.IntegerField(default=0),
        ),
    ]
