# Generated by Django 2.0 on 2019-02-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0008_auto_20190201_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('revised', 'revised'), ('sent', 'sent'), ('accepted', 'accepted'), ('pending', 'pending'), ('ready_to_revise', 'ready_to_revise'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
