# Generated by Django 2.0 on 2019-02-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0011_auto_20190201_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='job_link',
            field=models.URLField(null=True, unique=True),
        ),
    ]
