# Generated by Django 2.0 on 2019-02-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0012_auto_20190201_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('revised', 'revised'), ('sent', 'sent'), ('accepted', 'accepted'), ('pending', 'pending'), ('ready_to_revise', 'ready_to_revise'), ('rejected', 'rejected'), ('team_denied', 'team_denied')], default='pending', max_length=100),
        ),
    ]
