# Generated by Django 2.0 on 2019-01-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20181121_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postshift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='scheduledshift',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='PostShift',
        ),
        migrations.DeleteModel(
            name='ScheduledShift',
        ),
    ]
